CREATE TABLE clientes (
    id NUMBER GENERATED ALWAYS AS IDENTITY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) NOT NULL UNIQUE,
    cpf VARCHAR2(11) NOT NULL UNIQUE,
    CONSTRAINT clientes_pk PRIMARY KEY (id)
);