CREATE OR REPLACE VIEW view_saldo_por_cliente AS
SELECT
    c.ID AS CLIENTE_ID, c.NOME,
    COUNT(c2.NUMERO) AS NUMERO_DE_CONTAS,
    COALESCE(SUM(c2.SALDO), 0) AS SALDO_TOTAL
FROM CLIENTES c
LEFT JOIN CONTAS c2 ON c.ID = c2.CLIENTE_ID
GROUP BY c.ID, c.NOME;